#!/bin/bash

echo "Using jenkins @ $JENKINS_URL"

echo "Download jenkins-cli.jar"
curl -O "$JENKINS_URL/jnlpJars/jenkins-cli.jar"

echo "Login $JENKINS_USER"
java -jar jenkins-cli.jar login --username "$JENKINS_USER" --password "$JENKINS_PASSWORD"

echo "Register container $NODE_NAME as slave"
java -jar jenkins-cli.jar create-node "$NODE_NAME" << EOF
<slave>
    <name>$NODE_NAME</name>
    <description>$NODE_NAME for $NODE_LABEL</description>
    <remoteFS>/var/jenkins_slave/</remoteFS>
    <numExecutors>1</numExecutors>
    <mode>NORMAL</mode>
    <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
    <launcher class="hudson.slaves.JNLPLauncher"/>
    <label>$NODE_LABEL</label>
    <nodeProperties/>
</slave>
EOF

echo "Download slave.jar"
curl -O "$JENKINS_URL/jnlpJars/slave.jar"

echo "Connect slave to master"
java -jar slave.jar -jnlpCredentials "$JENKINS_USER:$JENKINS_PASSWORD" -jnlpUrl "$JENKINS_URL/computer/$NODE_NAME/slave-agent.jnlp"

